import { ItemData } from "./itemData";
import * as bullet from "./itemBulletData";
import * as itemType from './itemConst';

/* 
* -- ReadMe!! --
* アイテムはここで定義します。
* classifyにはitemType.○○を指定してください。
* ECTまたは上記以外だと未分類項目に入れられます。画面に表示されないので未採用置き場として活用してください。
* efficiencyは[]内に'',''で繋ぐと改行されます。
*/

export const ITEMS: ItemData[] = [
    // ここはテンプレです!追加するなら下に入れてね。
    {
        item_name: '敢えて言わせてもらおう、テンプレートであると!',
        items_avatar: '',
        classify: itemType.ECT,
        fire_mode: '中村悠一',
        reliability: '',
        r_point_blank: '',
        r_short: '',
        r_middle: '',
        r_long: '',
        penetration: bullet.CAL_50AE_PNT,
        non_penetration_damage: bullet.CAL_50AE_MIN,
        penetration_damage: bullet.CAL_50AE_MAX,
        range: '',
        mag_round: '',
        kinryoku: '',
        size: '',
        silence: '',
        item_value: '',
        mag_value: '',
        cartridge: '',
        item_width: '',
        item_weight: '',
        efficiency: [
            '君の存在に心奪われた男',
            '我慢弱く、落ち着きのない男',
            'ガンダムを越えようと愚行を繰り返した男',
            '気持ち悪い男',
            '仮面の男'
        ],
        note: '乙女座'
    },
    // ここから記入

    // #region ライフル
    //AAC MPW 300 BLACKOUT
    {
        /*アイテム名*/item_name: 'AAC MPW 300 BLACKOUT',
        /*画像*/items_avatar: 'assets/img/Rifle/AAC_MPW_300_BLACKOUT.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-40※',
        /*近距離*/r_short: '-20※',
        /*中距離*/r_middle: '-10',
        /*遠距離*/r_long: '-30',
        /*貫通力*/penetration: bullet.CAL_300BLK_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_300BLK_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_300BLK_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '5',
        /*本体価格*/item_value: '$3,300[13]',
        /*マガジン価格*/mag_value: '$100[12]',
        /*弾薬*/cartridge: '7.62mm×35(.300 AAC Blackout)',
        /*全長*/item_width: '805mm',
        /*重量*/item_weight: '4,010g',
        /*機能*/efficiency: [
            'サプレッサー装着不可。音の方向感知の必要達成値+5'
            , 'HP・AP・亜音速弾使用不可',
            '※次R同一目標攻撃時+15%'
        ],
        /*説明*/note: 'AAC社の多目的ライフル。MP5SDを代替する目的で開発され、.300 AAC Blackout(300 BLK)用の12.5インチバレルとAAC 762-SDN-6サイレンサーが標準装備されている。'
    },
    //Colt_M4A1_CQBR
    {
        /*アイテム名*/item_name: 'Colt M4A1 CQBR',
        /*画像*/items_avatar: 'assets/img/Rifle/Colt_M4A1_CQBR.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-30※',
        /*近距離*/r_short: '-15※',
        /*中距離*/r_middle: '-2',
        /*遠距離*/r_long: '-27',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '250m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両6/片8',
        /*CP*/size: '2×3',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2000[13]',
        /*マガジン価格*/mag_value: '$10[10]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '743mm',
        /*重量*/item_weight: '2,700g',
        /*機能*/efficiency: ['狙撃-35%', '※次R同一目標攻撃時+20%'],
        /*説明*/note: 'M4 カービンをさらに短銃身化した銃。SWATなどの特殊部隊で使用されていた。'
    },
    //FN SCAR-H
    {
        /*アイテム名*/item_name: 'FN SCAR-H',
        /*画像*/items_avatar: 'assets/img/Rifle/FN_SCARH.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-25※',
        /*中距離*/r_middle: '-5',
        /*遠距離*/r_long: '-25',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片8★',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$1,300[11]',
        /*マガジン価格*/mag_value: '$30[9]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '777/863mm',
        /*重量*/item_weight: '3,510g',
        /*機能*/efficiency: [
            'フル-10%',
            '狙撃-10%',
            '※次R同一目標攻撃時+20%',
            '★片手-20%',
            'マガジンは通常の他、6.5mmクリードモア弾が購入できる。このデータから遠距離の命中+10、狙撃+20。'
        ],
        /*説明*/note: '強力な7.62mmを使用する特殊部隊用戦闘アサルトライフル。US SOCOMにて採用され「Mk 17」と命名されている。モジュラーライフルとして設計されており、ストックやバレル、ハンドガードなどを交換することで軽機関銃からDME、PDWなどとして運用することもできる。'
    },
    {
        /*アイテム名*/item_name: 'FN SCAR-H (6.8mm仕様)',
        /*画像*/items_avatar: 'assets/img/Rifle/FN_SCARH.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-25※',
        /*中距離*/r_middle: '-5',
        /*遠距離*/r_long: '-15',
        /*貫通力*/penetration: bullet.CAL_65CREED_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_65CREED_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_65CREED_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片8★',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$1,300[11]',
        /*マガジン価格*/mag_value: '$60[10]',
        /*弾薬*/cartridge: '6.5mmクリードモア',
        /*全長*/item_width: '777/863mm',
        /*重量*/item_weight: '3,510g',
        /*機能*/efficiency: [
            'フル-10%',
            '狙撃+10%',
            '※次R同一目標攻撃時+20%',
            '★片手-20%'
        ],
        /*説明*/note: '6.5mmクリードモア弾を使用する特殊部隊用戦闘アサルトライフル。US SOCOMにて採用され「Mk 17」と命名されている。モジュラーライフルとして設計されており、ストックやバレル、ハンドガードなどを交換することで軽機関銃からDME、PDWなどとして運用することもできる。'
    },
    //H&K HK416A5
    {
        /*アイテム名*/item_name: 'H&K HK416A5',
        /*画像*/items_avatar: 'assets/img/Rifle/HK_HK416A5.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-30※',
        /*近距離*/r_short: '-15※',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-25',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2,500[13]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '848/944mm',
        /*重量*/item_weight: '3,560g',
        /*機能*/efficiency: [
            '狙撃-20%', '※次R同一目標攻撃時+15%'
        ],
        /*説明*/note: 'コンペ参加のために全面改修されたHK416。操作性が向上した他、マガジンがM4規格に変更され共用可能になった。'
    },
    //H&K HK416C
    {
        /*アイテム名*/item_name: 'H&K HK416C',
        /*画像*/items_avatar: 'assets/img/Rifle/HK_HK416C.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '99[98]',
        /*至近*/r_point_blank: '-25※',
        /*近距離*/r_short: '-10※',
        /*中距離*/r_middle: '-5',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両6/片8',
        /*CP*/size: '2×3',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2,000[13]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '560/690mm',
        /*重量*/item_weight: '2,960g',
        /*機能*/efficiency: [
            'フル-10%',
            '狙撃-40%',
            '※次R同一目標攻撃時+15%'
        ],
        /*説明*/note: 'HK416を8.9インチ銃身とCQBストックに換装したいわゆるCQBモデル。狭所での取り回しは良いが、信頼性に問題がある。'
    },
    //H&K HK417
    {
        /*アイテム名*/item_name: 'H&K HK417',
        /*画像*/items_avatar: 'assets/img/Rifle/HK_HK417.png',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[99]',
        /*至近*/r_point_blank: '-40※',
        /*近距離*/r_short: '-20※',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-25',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '400m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2,500[13]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '905/985mm',
        /*重量*/item_weight: '4,250g',
        /*機能*/efficiency: [
            'フル-20%',
            '狙撃-15%',
            '※次R同一目標攻撃時+15%'
        ],
        /*説明*/note: 'HK416の7.62mm×51弾モデル。7.62mm×51弾クラスのバトルライフルの有用性が再評価されたことから開発された。G3と比べ、遠距離射撃時における精度が不足している。'
    },
    //H&K M110A1
    {
        /*アイテム名*/item_name: 'H&K M110A1',
        /*画像*/items_avatar: 'assets/img/Rifle/HK_M110A1.jpg',
        /*種別*/classify: itemType.DMR,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-50※',
        /*近距離*/r_short: '-30※',
        /*中距離*/r_middle: '-10',
        /*遠距離*/r_long: '-10',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '600m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2,500[13]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '905mm',
        /*重量*/item_weight: '4,100g',
        /*機能*/efficiency: [
            '狙撃-0%',
            '※次R同一目標攻撃時+15%'
        ],
        /*説明*/note: 'ナイツアーマメント社によって開発されたセミオートライフル。アメリカ陸軍で使用されていたM110(SR25)には構造的な問題があり、また市街戦では全長と重量が過大であると言われていた。そこで白羽の矢が立ったのはHK社のHK417であり、軽量小型化改修が加えられたものがM110A1として採用された。'
    },
    //Kalashnikov Concern AK-12 (2020 model)
    {
        item_name: 'Kalashnikov Concern AK-12 (2020 model)',
        items_avatar: 'assets/img/Rifle/Kalashnikov_Concern_AK_12.jpg',
        classify: itemType.RF,
        fire_mode: 'S/2/F',
        reliability: '□□[□]',
        r_point_blank: '-40※',
        r_short: '-20※',
        r_middle: '-0',
        r_long: '-20',
        penetration: bullet.CAL_545X39_PNT,
        non_penetration_damage: bullet.CAL_545X39_MIN,
        penetration_damage: bullet.CAL_545X39_MAX,
        range: '300m',
        mag_round: '30',
        kinryoku: '両6/片8☆',
        size: '2×4',
        silence: '2',
        item_value: '$1100[9]',
        mag_value: '$10[6]',
        cartridge: '5.45mm×39',
        item_width: '880/940mm',
        item_weight: '3,300g',
        efficiency: [
            '狙撃-25%',
            '※次R同一目標攻撃時+20%',
            '★片手-20%'
        ],
        note: 'AKファミリーの新型。フリーフローティングバレルに変更され、遠距離の精度が向上した。一部のパーツがM4/M16と互換性がある。最新のものはフォールディングストックが採用され、運用しやすくなった。'
    },
    //Remington R5 RGP
    {
        /*アイテム名*/item_name: 'Remington R5 RGP',
        /*画像*/items_avatar: 'assets/img/Rifle/Remington_R5_RGP.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-30※',
        /*近距離*/r_short: '-15※',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-25',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '250m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両6/片8★',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$900[9]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '777/863mm',
        /*重量*/item_weight: '3,160g',
        /*機能*/efficiency: [
            '狙撃-30%',
            '※次R同一目標攻撃時+20%',
            '★片手-20%'
        ],
        /*説明*/note: 'ショートストロークのガスピストンを採用したAR-15クローン。高い信頼性と耐久性を持ち、分解も簡単。'
    },
    //SA M14 EBR
    {
        /*アイテム名*/item_name: 'SA M14 EBR',
        /*画像*/items_avatar: 'assets/img/Rifle/SA_M14_EBR.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-42※',
        /*近距離*/r_short: '-22※',
        /*中距離*/r_middle: '-2',
        /*遠距離*/r_long: '-22',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '500m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2500[10]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '1,120mm',
        /*重量*/item_weight: '4,560g',
        /*機能*/efficiency: [
            '狙撃-10%',
            'フル-10%',
            '※次R同一目標攻撃時+20%'
        ],
        /*説明*/note: 'M14を近代化改修した銃。M16やM4を超える射程距離と高威力を持つM14の再評価が始まり、軍倉庫に死蔵されていた物に全面的な改修を施した様々なモデルが実戦に多数投入されるようになった。これはセージ(Sage)社のEBR(Enhanced Battle Rifle)で、FRPや軽合金製のフォアエンド・ストックへの変更、ピカティニーレールによるモジュラーシステムの採用など、かなり大規模なカスタムが施されている。'
    },
    //SA SRSS Bulldog
    {
        /*アイテム名*/item_name: 'SA SRSS Bulldog',
        /*画像*/items_avatar: 'assets/img/Rifle/SA_SRSS_Bulldog.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-35※',
        /*近距離*/r_short: '-20※',
        /*中距離*/r_middle: '-5',
        /*遠距離*/r_long: '-30',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片8★',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2500[13]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '780mm',
        /*重量*/item_weight: '4,560g',
        /*機能*/efficiency: [
            '狙撃-20%',
            'フル-10%',
            '※次R同一目標攻撃時+15%',
            '★片手-20%'
        ],
        /*説明*/note: 'M14を短小にしたライフル。動きや操作性に支障がなく、光学機器などのアタッチメントを装着できるライフルが欲しいという要望から、引退した米国海兵隊の軍曹によって開発された。'
    },
    //Steyr_Mannlicher_Steyr_AUG_9mm
    {
        /*アイテム名*/item_name: 'Steyr Mannlicher Steyr AUG 9mm',
        /*画像*/items_avatar: 'assets/img/Rifle/Steyr_Mannlicher_Steyr_AUG_9mm.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-20',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '25',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '2×4(+1×1)',
        /*消音LV*/silence: '3',
        /*本体価格*/item_value: '$900[9]',
        /*マガジン価格*/mag_value: '$6[6]',
        /*弾薬*/cartridge: '9mm×19',
        /*全長*/item_width: '665mm',
        /*重量*/item_weight: '3,300g',
        /*機能*/efficiency: ['スコープLv1(1×1)標準装備'],
        /*説明*/note: 'オーストリアのシュタイヤー・マンリヒャー (Steyr Mannlicher) 社の開発したSMG。AUGはアルメー・ウニヴァザール・ゲヴェーア（Armee Universal Gewehr、軍用汎用小銃の意）の頭文字に由来する市販名。これは9mm弾を使用する短機関銃モデルである。'
    },
    //Winchester Model 1895 Modernised
    {
        /*アイテム名*/item_name: 'Winchester Model 1895 Modernised',
        /*画像*/items_avatar: 'assets/img/Rifle/Winchester_1895_modernised.jpg',
        /*種別*/classify: itemType.DMR,
        /*射撃モード*/fire_mode: 'Lever-action',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-25※',
        /*中距離*/r_middle: '-5',
        /*遠距離*/r_long: '-35',
        /*貫通力*/penetration: bullet.CAL_762X54R_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X54R_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X54R_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '5(T)',
        /*必要筋力*/kinryoku: '両5/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$1500[10]',
        /*マガジン価格*/mag_value: '$10[6] 弾のみ20発',
        /*弾薬*/cartridge: '7.62mm×54R',
        /*全長*/item_width: '965mm',
        /*重量*/item_weight: '2,500g',
        /*機能*/efficiency: [
            '狙撃-30%',
            '※次R同一目標攻撃時+15%'
        ],
        /*説明*/note: 'ウィンチェスター社が初めて箱型弾倉を採用したレバーアクション小銃。かのルーズベルトもライオンへの最良の銃として賞賛した。現在は若干のアレンジが加えられながら日本のミロクで製造されている。最新モデルはレイルシステムに対応している。'
    },
    // Mk-18 Mjornir
    {
        /*アイテム名*/item_name: 'Mk-18 Mjornir',
        /*画像*/items_avatar: 'assets/img/Rifle/cr7338.jpg',
        /*種別*/classify: itemType.DMR,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-57※',
        /*近距離*/r_short: '-37※',
        /*中距離*/r_middle: '-15',
        /*遠距離*/r_long: '-20',
        /*貫通力*/penetration: bullet.CAL_338LM_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_338LM_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_338LM_MAX,
        /*射程*/range: '1500m',
        /*弾数*/mag_round: '10',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '3×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2500[12]',
        /*マガジン価格*/mag_value: '$30[7]',
        /*弾薬*/cartridge: '.338 Lapua Magnum',
        /*全長*/item_width: '980mm',
        /*重量*/item_weight: '5,800g',
        /*機能*/efficiency: [
            '狙撃-30%',
            '※次R同一目標攻撃時+20%'
        ],
        /*説明*/note: 'S.W.O.R.D.が製造している大口径ライフル。'
    },
    // SIG Sauer 716
    {
        /*アイテム名*/item_name: 'SIG 716i TREAD',
        /*画像*/items_avatar: 'assets/img/Rifle/r716i-16b-trd-right-web.jpg',
        /*種別*/classify: itemType.DMR,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-19※',
        /*中距離*/r_middle: '-3',
        /*遠距離*/r_long: '-18',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '400m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$1500[9]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '940mm',
        /*重量*/item_weight: '3,850g',
        /*機能*/efficiency: [
            '狙撃-10%',
            '※次R同一目標攻撃時+20%'
        ],
        /*説明*/note: 'SIGの最新軽量ライフル。DI式で精度が高く、射撃精度の向上を目指した設計となっている。インド陸軍や英国CTSFOで使用されている。TREADシリーズの伝統である小型ガスブロック、フリーフローティングM-LOKハンドガード、Magpul伸縮ストックを引き継ぐ。'
    },
    // SIG Sauer MCX
    {
        /*アイテム名*/item_name: 'SIG Sauer MCX',
        /*画像*/items_avatar: 'assets/img/Rifle/Sig_sauer_mcx.jpg',
        /*種別*/classify: itemType.RF,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-30※',
        /*近距離*/r_short: '-15※',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-25',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2,500[10]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '',
        /*重量*/item_weight: '',
        /*機能*/efficiency: [
            '狙撃-20%',
            '※次R同一目標攻撃時+15%'
        ],
        /*説明*/note: 'SIGの汎用ライフルMCX。伝統的なショートストロークガスピストン式を採用している。'
    },
    // SIG Sauer MCX SPEAR
    {
        /*アイテム名*/item_name: 'SIG Sauer MCX SPEAR',
        /*画像*/items_avatar: 'assets/img/Rifle/mcx-spear-web-16-2.jpg',
        /*種別*/classify: itemType.DMR,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[00]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-22※',
        /*中距離*/r_middle: '-6',
        /*遠距離*/r_long: '-21',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '400m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2,500[10]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '',
        /*重量*/item_weight: '',
        /*機能*/efficiency: [
            '狙撃-20%',
            '※次R同一目標攻撃時+20%'
        ],
        /*説明*/note: 'SIGの汎用ライフルMCXのバリエーション。大口径ライフルだが折りたたみ可能なストックが採用されており、携行性に優れている。民間仕様が一般販売されている。'
    },
    //GIAT_FAMAS_felin
    {
            /*アイテム名*/item_name: 'GIAT FAMAS-felin',
            /*画像*/items_avatar: 'assets/img/Rifle/GIAT_FAMAS_felin.png',
            /*種別*/classify: itemType.RF,
            /*射撃モード*/fire_mode: 'S/3/F',
            /*信頼性*/reliability: '00[99]',
            /*至近*/r_point_blank: '-30※',
            /*近距離*/r_short: '-15※',
            /*中距離*/r_middle: '0',
            /*遠距離*/r_long: '-25',
            /*貫通力*/penetration: bullet.CAL_556X45_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
            /*射程*/range: '450m',
            /*弾数*/mag_round: '30',
            /*必要筋力*/kinryoku: '両6/片8★',
            /*CP*/size: '2×4',
            /*消音LV*/silence: '2',
            /*本体価格*/item_value: '$3,000[14]',
            /*マガジン価格*/mag_value: '$10[6]',
            /*弾薬*/cartridge: '5.56mm×45',
            /*全長*/item_width: '757mm',
            /*重量*/item_weight: '3,800g',
            /*機能*/efficiency: [
            '狙撃-25%',
            '※次R同一目標攻撃時+15%',
            'バイポッド内蔵',
            'スコープ類使用時命中率+5%',
            '★片手-20%'
        ],
            /*説明*/note: '従来のFAMASの問題であった照準器が制限される特徴的なキャリングハンドルを廃し、一般的なピカティニー・レール付きの物に改良したモデル。レールの高度が下がり、照準の誤差が緩和されている。本来は「統合型光学照準システム」を専用サイトとして有し、遮蔽物に隠れたまま射撃が可能になっている。'
    },
    //IMI_Tavor_TAR_21
    {
            /*アイテム名*/item_name: 'IMI Tavor TAR-21',
            /*画像*/items_avatar: 'assets/img/Rifle/IMI_Tavor_TAR_21.jpg',
            /*種別*/classify: itemType.RF,
            /*射撃モード*/fire_mode: 'S/F',
            /*信頼性*/reliability: '□[□]',
            /*至近*/r_point_blank: '-25※',
            /*近距離*/r_short: '-15※',
            /*中距離*/r_middle: '0',
            /*遠距離*/r_long: '-25',
            /*貫通力*/penetration: bullet.CAL_556X45_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
            /*射程*/range: '300m',
            /*弾数*/mag_round: '30',
            /*必要筋力*/kinryoku: '両6/片8★',
            /*CP*/size: '2×4(1×1)',
            /*消音LV*/silence: '2',
            /*本体価格*/item_value: '$2,500[13]',
            /*マガジン価格*/mag_value: '$10[6]',
            /*弾薬*/cartridge: '5.56mm×45',
            /*全長*/item_width: '725mm',
            /*重量*/item_weight: '2,800g',
            /*機能*/efficiency: [
            '狙撃-25%',
            '※次R同一目標攻撃時+15%',
            'ダットサイト(1×1)標準装備',
            '★片手-20%'
        ],
            /*説明*/note: 'MARSサイトと呼ばれる専用のサイトを標準装備する、IMI社製の新型アサルトライフル。外観のストックにはAUGと同様のセンサテック（合成樹脂）を採用し、内部パーツにはセンサテックとアルミニウム合金を多用している。これにより約2,800gという、アサルトライフルでは1、2を争う軽さを誇り、腐食にも強い。'
    },
    //IMI_Tavor_X95
    {
            /*アイテム名*/item_name: 'IMI Tavor X95',
            /*画像*/items_avatar: 'assets/img/Rifle/IMI_Tavor_X95.jpg',
            /*種別*/classify: itemType.RF,
            /*射撃モード*/fire_mode: 'S/F',
            /*信頼性*/reliability: '□[99]',
            /*至近*/r_point_blank: '-25※',
            /*近距離*/r_short: '-15※',
            /*中距離*/r_middle: '-5',
            /*遠距離*/r_long: '-30',
            /*貫通力*/penetration: bullet.CAL_556X45_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
            /*射程*/range: '250m',
            /*弾数*/mag_round: '30',
            /*必要筋力*/kinryoku: '両5/片8',
            /*CP*/size: '2×3',
            /*消音LV*/silence: '2',
            /*本体価格*/item_value: '$3,000[13]',
            /*マガジン価格*/mag_value: '$10[6]',
            /*弾薬*/cartridge: '5.56mm×45',
            /*全長*/item_width: '590mm',
            /*重量*/item_weight: '2,950g',
            /*機能*/efficiency: [
            '狙撃-35%',
            '※次R同一目標攻撃時+15%',
        ],
            /*説明*/note: 'サブマシンガン並みの全長を実現した、TAR-21の派生モデル。全長は590mmだが、重量は2,950gと、意外にTAR-21より重いのが特徴。旧称のMTAR-21(マイクロ・タボール)がニックネームとして併記されることもある。'
    },
    //RSAF_Enfield_L85A2
    {
            /*アイテム名*/item_name: 'RSAF_Enfield_L85A2',
            /*画像*/items_avatar: 'assets/img/Rifle/RSAF_Enfield_L85A2.jpg',
            /*種別*/classify: itemType.RF,
            /*射撃モード*/fire_mode: 'S/F',
            /*信頼性*/reliability: '00[99]',
            /*至近*/r_point_blank: '-35※',
            /*近距離*/r_short: '-20※',
            /*中距離*/r_middle: '0',
            /*遠距離*/r_long: '-20',
            /*貫通力*/penetration: bullet.CAL_556X45_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
            /*射程*/range: '350m',
            /*弾数*/mag_round: '30',
            /*必要筋力*/kinryoku: '両6/片8★',
            /*CP*/size: '2×4',
            /*消音LV*/silence: '2',
            /*本体価格*/item_value: '$2,000[11]',
            /*マガジン価格*/mag_value: '$10[6]',
            /*弾薬*/cartridge: '5.56mm×45',
            /*全長*/item_width: '785mm',
            /*重量*/item_weight: '3,820g',
            /*機能*/efficiency: [
            '狙撃-20%',
            '※次R同一目標攻撃時+15%',
            '★片手-20%'
        ],
            /*説明*/note: '問題の多かったL85A1を、H&K社が改修を行ったモデル。多くの改良が加えられており、その中でも作動不良の回数は平均25,200発に1回と、劇的に低下した。'
    },
    //RSAF_Enfield_L85A3
    {
            /*アイテム名*/item_name: 'RSAF_Enfield_L85A3',
            /*画像*/items_avatar: 'assets/img/Rifle/RSAF_Enfield_L85A3.jpg',
            /*種別*/classify: itemType.RF,
            /*射撃モード*/fire_mode: 'S/F',
            /*信頼性*/reliability: '00[99]',
            /*至近*/r_point_blank: '-30※',
            /*近距離*/r_short: '-20※',
            /*中距離*/r_middle: '0',
            /*遠距離*/r_long: '-20',
            /*貫通力*/penetration: bullet.CAL_556X45_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
            /*射程*/range: '350m',
            /*弾数*/mag_round: '30',
            /*必要筋力*/kinryoku: '両6/片8★',
            /*CP*/size: '2×4',
            /*消音LV*/silence: '2',
            /*本体価格*/item_value: '$3,500[14]',
            /*マガジン価格*/mag_value: '$10[6]',
            /*弾薬*/cartridge: '5.56mm×45',
            /*全長*/item_width: '785mm',
            /*重量*/item_weight: '3,720g',
            /*機能*/efficiency: [
            '狙撃-20%',
            '※次R同一目標攻撃時+15%',
            '★片手-20%'
        ],
            /*説明*/note: 'L85A2の発展型。A2からの主な改良点は、100gの軽量化、迷彩効果を高めるFDE（フラットダークアース: Flat Dark Earth）カラーのコーティング、銃本体上部とボトム部にはピカティニー規格レールや前部グリップの改良、光学照準器の更新等となっている'
    },
    // #endregion

    // #region SR
    //H&K SL9SD
    {
        /*アイテム名*/item_name: 'H&K SL9SD',
        /*画像*/items_avatar: 'assets/img/sRifle/HK_SL9SD.png',
        /*種別*/classify: itemType.SR,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-25※',
        /*中距離*/r_middle: '-5',
        /*遠距離*/r_long: '-20',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '500m',
        /*弾数*/mag_round: '10',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×6',
        /*消音LV*/silence: '5',
        /*本体価格*/item_value: '$2,500[13]',
        /*マガジン価格*/mag_value: '$110[13]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '980mm',
        /*重量*/item_weight: '3,950g',
        /*機能*/efficiency: [
            '狙撃+0%',
            'サプレッサー装着不可。音の方向感知-20%、必要達成値+5',
            'HP・AP・亜音速弾使用不可',
            '※次R同一目標攻撃時+20%'
        ],
        /*説明*/note: 'H&K社が民間モデルSL8をベースに開発した消音狙撃銃。サプレッサーを標準装備している。SL8をベースにしたとの通りH&K G36の民生用モデルの派生型の1つであり、SR9とは無関係である。'
    },
    // #endregion

    // #region 対物
    //Barret_XM500
    {
        /*アイテム名*/item_name: 'Barret XM500',
        /*画像*/items_avatar: 'assets/img/amRifle/Barret_XM500.png',
        /*種別*/classify: itemType.AMR,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-60※',
        /*近距離*/r_short: '-40※',
        /*中距離*/r_middle: '-30',
        /*遠距離*/r_long: '-20',
        /*貫通力*/penetration: bullet.CAL_50BGM_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_50BGM_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_50BGM_MAX,
        /*射程*/range: '2000m',
        /*弾数*/mag_round: '10',
        /*必要筋力*/kinryoku: '両14/片-',
        /*CP*/size: '5×6(+1×3)',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$8000[15]',
        /*マガジン価格*/mag_value: '$30[9]',
        /*弾薬*/cartridge: '12.7mm×99',
        /*全長*/item_width: '1,168mm',
        /*重量*/item_weight: '11,800g',
        /*機能*/efficiency: ['狙撃+10%',
            '※次R同一目標攻撃時+10%',
            'スコープLv3(1×3)、バイポッド内蔵',
            '対車両'
        ],
        /*説明*/note: 'バレット社製の最新型対物ライフル。M82/M107の発展後継型として開発され、2006年に発表されたアメリカ陸軍向けのプロトタイプ。作動方式がM82のショートリコイル方式からガスオペレーション・ロータリーボルトロック方式に変更されている。このため、銃身は固定されており、M82より精度的には有利な構造となっている。'
    },
    //Sero_International_GM6_Lynx
    {
        /*アイテム名*/item_name: 'Sero International GM6 Lynx',
        /*画像*/items_avatar: 'assets/img/amRifle/Sero_International_GM6_Lynx.jpg',
        /*種別*/classify: itemType.AMR,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-60※',
        /*近距離*/r_short: '-40※',
        /*中距離*/r_middle: '-30',
        /*遠距離*/r_long: '-20',
        /*貫通力*/penetration: bullet.CAL_50BGM_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_50BGM_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_50BGM_MAX,
        /*射程*/range: '1600m',
        /*弾数*/mag_round: '5',
        /*必要筋力*/kinryoku: '両10/片-',
        /*CP*/size: '4×5',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$8000[15]',
        /*マガジン価格*/mag_value: '$100[9]',
        /*弾薬*/cartridge: '12.7mm×99',
        /*全長*/item_width: '914/1,114mm',
        /*重量*/item_weight: '10,500g',
        /*機能*/efficiency: [
            '狙撃-0%',
            '※次R同一目標攻撃時+15%',
            '対車両'
        ],
        /*説明*/note: 'ハンガリー製の対物ライフル。頻発する自動車による自爆テロを阻止する目的で造られた。空挺部隊の使用も考慮されているため他の対物ライフルと比べて小型で軽量、反動も小さい。その代わり精度は多少劣る。'
    },
    // #endregion 

    // #region ショットガン
    //Armscor VR80-A
    {
        /*アイテム名*/item_name: 'Armscor VR80-A',
        /*画像*/items_avatar: 'assets/img/Shotgun/Armscor_VR80_A.jpg',
        /*種別*/classify: itemType.SG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-10',
        /*近距離*/r_short: '+10',
        /*中距離*/r_middle: '+20',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_12G_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_12G_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_12G_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '5',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$900[8]',
        /*マガジン価格*/mag_value: '$20(9発)[9] $50(19発)[12]',
        /*弾薬*/cartridge: '12ゲージ(OO)',
        /*全長*/item_width: '1,016mm',
        /*重量*/item_weight: '3,750g',
        /*機能*/efficiency: [
            '部位狙い不可',
            '距離別貫通/ダメージ ',
            bullet.CAL_12G_RANGE,
            '装弾数19のマガジン使用時隠匿判定-20%'
        ],
        /*説明*/note: '米Armscor社が近年発売した箱型弾倉式セミオート散弾銃。ストックやグリップがAR15と互換性があり見た目も操作性も似ており、かつ安価なためシェアを急速に拡大させている。'
    },
    //Daewoo U.S.AS12
    {
        /*アイテム名*/item_name: 'Daewoo U.S.AS12',
        /*画像*/items_avatar: 'assets/img/Shotgun/Daewoo_U_S_AS12.jpg',
        /*種別*/classify: itemType.SG,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-12',
        /*近距離*/r_short: '+8',
        /*中距離*/r_middle: '+18',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_12G_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_12G_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_12G_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '10/20',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '3×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$3000[13]',
        /*マガジン価格*/mag_value: '$20(10発)[10] $40(20発)[10]',
        /*弾薬*/cartridge: '12ゲージ(OO)',
        /*全長*/item_width: '960mm',
        /*重量*/item_weight: '5,500g',
        /*機能*/efficiency: [
            '部位狙い不可',
            '距離別貫通/ダメージ ',
            bullet.CAL_12G_RANGE,
            '20発マガジン(1×2)はマガジンポーチに入らない。'],
        /*説明*/note: 'アメリカ合衆国のギルバート・エクイップメント社が設計し大韓民国の大宇社が製造しているフルオート射撃可能なショットガン。デザインはこれまでのショットガンと異なり、ボックスマガジンがグリップの前方に配置され、マガジンの着脱が容易となっている点はむしろM4カービンのようなアサルトライフル（カービン）に近い。'
    },
    //Fostech Origin-12
    {
        /*アイテム名*/item_name: 'Fostech Origin-12',
        /*画像*/items_avatar: 'assets/img/Shotgun/Fostech_Origin_12.jpg',
        /*種別*/classify: itemType.SG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-10',
        /*近距離*/r_short: '+10',
        /*中距離*/r_middle: '+20',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_12G_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_12G_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_12G_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '10',
        /*必要筋力*/kinryoku: '両6/片8★',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$1300[12]',
        /*マガジン価格*/mag_value: '$20(10発)[10] $100(20発)[13]',
        /*弾薬*/cartridge: '12ゲージ(OO)',
        /*全長*/item_width: '705/920mm',
        /*重量*/item_weight: '4,130g',
        /*機能*/efficiency: [
            '部位狙い不可',
            '距離別貫通/ダメージ ',
            bullet.CAL_12G_RANGE,
            '装弾数20のマガジン使用時隠匿判定-20%',
            '★片手-20%',
            'スラグ弾命中修正[-45/-45/-40/-40]'
        ],
        /*説明*/note: 'Saiga12を参考にして米国で造られた箱型弾倉式セミオート散弾銃。AR15と互換性があり、反動が少なく扱いやすいため非常に人気。"地球最速"が売り文句。'
    },
    //Franchi SPAS-15
    {
        /*アイテム名*/item_name: 'Franchi SPAS-15',
        /*画像*/items_avatar: 'assets/img/Shotgun/Franchi_SPAS_15.jpg',
        /*種別*/classify: itemType.SG,
        /*射撃モード*/fire_mode: 'S/Pomp',
        /*信頼性*/reliability: '99[98]/□[00]',
        /*至近*/r_point_blank: '-10',
        /*近距離*/r_short: '+10',
        /*中距離*/r_middle: '+20',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_12G_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_12G_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_12G_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '6',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$1000[10]',
        /*マガジン価格*/mag_value: '$20(10発)[10]',
        /*弾薬*/cartridge: '12ゲージ(OO)',
        /*全長*/item_width: '1,000mm',
        /*重量*/item_weight: '3,900g',
        /*機能*/efficiency: [
            '部位狙い不可',
            '距離別貫通/ダメージ ',
            bullet.CAL_12G_RANGE
        ],
        /*説明*/note: 'イタリアのフランキ社の散弾銃。Franchi Special Purpose Automatic Shotgun 15 略称:SPAS-15。先に開発されたSPAS-12は、セミオートとポンプアクション式の2つの射撃モードを持ち合わせていたが、従来同様のチューブ式弾倉のため、再装填に時間が掛かるという欠点を抱えており、また使用中に弾種を変更することが困難だった。SPAS-15は、こういったSPAS-12の問題点を改善することを目的にイタリア軍の要請で開発が始められたが、アメリカ軍で進められていたCAW（クローズ・アサルト・ウェポン）計画のトライアルも意識されて開発された。'
    },
    //MetalStorm MAUL
    {
        /*アイテム名*/item_name: 'MetalStorm MAUL',
        /*画像*/items_avatar: 'assets/img/Shotgun/MetalStorm_MAUL.jpg',
        /*種別*/classify: itemType.SG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '98[96]',
        /*至近*/r_point_blank: '-15',
        /*近距離*/r_short: '+5',
        /*中距離*/r_middle: '+15',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_12G_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_12G_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_12G_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '5',
        /*必要筋力*/kinryoku: '銃準拠(両6/片8)',
        /*CP*/size: '1×2(単独時2×3)',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2000[10]',
        /*マガジン価格*/mag_value: '$50[10]',
        /*弾薬*/cartridge: '12ゲージ(OO)',
        /*全長*/item_width: '400mm',
        /*重量*/item_weight: '816g',
        /*機能*/efficiency: [
            '部位狙い不可',
            '距離別貫通/ダメージ',
            bullet.CAL_12G_RANGE,
            '補器(下)',
            '射撃ファンブル表+2',
            '特殊弾薬不可'
        ],
        /*説明*/note: 'オーストラリアの企業メタルストーム社が開発した、アンダーバレルに装着できる、銃身がチューブマガジンになっている電気発火式セミオートマチック散弾銃。 リロードは銃身ごと交換する。 従来の機械的な連発機構を廃した恩恵で軽量であり、電気制御のため安全性が高い。 契約終了で余った在庫が民間軍事会社に回されている。'
    },
    //MPS AA-12
    {
        /*アイテム名*/item_name: 'MPS AA-12',
        /*画像*/items_avatar: 'assets/img/Shotgun/MPS_AA_12.jpg',
        /*種別*/classify: itemType.SG,
        /*射撃モード*/fire_mode: 'F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-10',
        /*近距離*/r_short: '+10',
        /*中距離*/r_middle: '+20',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_12G_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_12G_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_12G_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '8',
        /*必要筋力*/kinryoku: '両6/片-',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$1000[12]',
        /*マガジン価格*/mag_value: '$10(8発)[10] $100(20発)[10]',
        /*弾薬*/cartridge: '12ゲージ(OO)',
        /*全長*/item_width: '966mm',
        /*重量*/item_weight: '4,760g',
        /*機能*/efficiency: [
            '部位狙い不可',
            '距離別貫通/ダメージ ',
            bullet.CAL_12G_RANGE
        ],
        /*説明*/note: 'フルオート機能を持つ散弾銃。新技術により片手でも射撃可能な低反動を実現している。強盗から身を守るために作られたと噂される。'
    },
    //TsNIITochMash KS-23M
    {
        /*アイテム名*/item_name: 'TsNIITochMash KS-23M',
        /*画像*/items_avatar: 'assets/img/Shotgun/TsNIITochMash_KS-23M.jpg',
        /*種別*/classify: itemType.SG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[00]',
        /*至近*/r_point_blank: '-10',
        /*近距離*/r_short: '+10',
        /*中距離*/r_middle: '+20',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_23MM_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_23MM_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_23MM_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '3(T)',
        /*必要筋力*/kinryoku: '両6/片8',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '2',
        /*本体価格*/item_value: '$2300[14]',
        /*マガジン価格*/mag_value: '$20(弾のみ10発)[10]',
        /*弾薬*/cartridge: '6.27ゲージ(OO)',
        /*全長*/item_width: '950/875mm',
        /*重量*/item_weight: '2,900g',
        /*機能*/efficiency: [
            '部位狙い不可',
            '距離別貫通/ダメージ ',
            bullet.CAL_23MM_RANGE
        ],
        /*説明*/note: '旧ソ連において1971年に開発されたポンプアクション式散弾銃。正式名称は「特殊作戦用23mmカービン」。ライフルドバレルを採用しているためカービン扱いとなっている。大口径であることから閃光弾などの特殊なランチャーとしても利用されることがあった。近年扱いに困ったロシアは特殊機材に区分した。'
    },
    // #endregion

    // #region SMG
    //AeroPrecision AR-57
    {
        /*アイテム名*/item_name: 'AeroPrecision AR-57',
        /*画像*/items_avatar: 'assets/img/SMG/AeroPrecision_AR_57.jpg',
        /*種別*/classify: itemType.PDW,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-20',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_57X28_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_57X28_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_57X28_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '50',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '2×4',
        /*消音LV*/silence: '3',
        /*本体価格*/item_value: '$1900[10]',
        /*マガジン価格*/mag_value: '$20[9]',
        /*弾薬*/cartridge: '5.7×28mm',
        /*全長*/item_width: '762mm',
        /*重量*/item_weight: '3,400g',
        /*機能*/efficiency: [
            'この弾倉(1×2)はマガジンポーチに入らない',
            '弾倉交換：[アイテム使用]2回',
            'スコープ系Lv2、3装着不可',
            'AR-15コンバージョンキット($3000[12])を購入することでフルオート発射が可能'
        ],
        /*説明*/note: '5.7×28mm弾仕様に改造したAR-15。M16/M4系で拡張性が高い。上部レールが短いため大きな照準器が装着できない。'
    },
    //Cz-Scorpion evo3 A1
    {
        /*アイテム名*/item_name: 'Cz-Scorpion evo3 A1',
        /*画像*/items_avatar: 'assets/img/SMG/Cz_scorpion_evo_3_a1.png',
        /*種別*/classify: itemType.SMG,
        /*射撃モード*/fire_mode: 'S/3/F',
        /*信頼性*/reliability: '□[99]',
        /*至近*/r_point_blank: '-20',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '2×3',
        /*消音LV*/silence: '3',
        /*本体価格*/item_value: '$900[6]',
        /*マガジン価格*/mag_value: '$6[6]',
        /*弾薬*/cartridge: '9mm×19',
        /*全長*/item_width: '410/660mm',
        /*重量*/item_weight: '2,700g',
        /*機能*/efficiency: [],
        /*説明*/note: 'チェコ製のポリマーフレーム短機関銃。発展途上国の法執行機関で採用例が見られる。その性能・価格・ブランドから、アメリカ市場では非常に人気の高いPCCであり、マグプル社含む各社から多くの拡張アクセサリーが販売されている。全自動射撃機能がついたA1 短機関銃と 民間用の半自動射撃限定である S1の2モデルがある。'
    },
    //Sig Sauer MPX
    {
        /*アイテム名*/item_name: 'Sig Sauer MPX',
        /*画像*/items_avatar: 'assets/img/Rifle/MPX.jpg',
        /*種別*/classify: itemType.SMG,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[99]',
        /*至近*/r_point_blank: '-20',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '0',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '2×3',
        /*消音LV*/silence: '3',
        /*本体価格*/item_value: '$900[6]',
        /*マガジン価格*/mag_value: '$6[6]',
        /*弾薬*/cartridge: '9mm×19',
        /*全長*/item_width: '410/660mm',
        /*重量*/item_weight: '2,700g',
        /*機能*/efficiency: [],
        /*説明*/note: 'Sig Sauerが設計・製造しているSMG。法執行機関、軍関係者、民間シューターの間で人気を博している。'
    },
    //Diamondback Firearms DBX
    {
        /*アイテム名*/item_name: 'Diamondback Firearms DBX',
        /*画像*/items_avatar: 'assets/img/SMG/Diamondback_Firearms_DBX.jpg',
        /*種別*/classify: itemType.PDW,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-10',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '-10',
        /*遠距離*/r_long: '-50',
        /*貫通力*/penetration: bullet.CAL_57X28_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_57X28_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_57X28_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '2×2',
        /*消音LV*/silence: '3',
        /*本体価格*/item_value: '$1300[10]',
        /*マガジン価格*/mag_value: '$20[9]',
        /*弾薬*/cartridge: '5.7×28mm',
        /*全長*/item_width: '380mm',
        /*重量*/item_weight: '1,300g',
        /*機能*/efficiency: [
            '※この弾倉(1×1)はFN Five-SeveNと共通。'
        ],
        /*説明*/note: 'DiamondBack社のAR-15派生のPDW。最近の流行であるFN57のマガジンを使用する。小型軽量でハンドリングが軽快。ストックを外したモデルがハンドガンとして扱われる事もある。'
    },
    //KBP Instrument Design Bureau PP-2000
    {
        /*アイテム名*/item_name: 'KBP Instrument Design Bureau PP-2000',
        /*画像*/items_avatar: 'assets/img/SMG/KBP_Instrument_Design_Bureau_PP_2000.jpg',
        /*種別*/classify: itemType.SMG,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-20',
        /*近距離*/r_short: '-2',
        /*中距離*/r_middle: '-2',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '20/44',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '2×2',
        /*消音LV*/silence: '3',
        /*本体価格*/item_value: '$2300[15]',
        /*マガジン価格*/mag_value: '$10(20発)[15]/$20(40発)[15]',
        /*弾薬*/cartridge: '9mm×19 7N31 +P+',
        /*全長*/item_width: '340/555mm',
        /*重量*/item_weight: '1,400g',
        /*機能*/efficiency: [
            '装弾数40のマガジン使用時:[隠匿判定]-20%',
            'DP-1'
        ],
        /*説明*/note: 'ロシア製SMG。重量は弾薬なしの状態で1.5kgと非常に軽量。9x19mmパラベラム弾用の薬室を持つうえ、ロシア製の新型弾薬である7N31 +P+徹甲弾を利用できるよう、特別な設計が施されている。'
    },
    //KRISS Vector
    {
        /*アイテム名*/item_name: 'KRISS Vector',
        /*画像*/items_avatar: 'assets/img/SMG/KRISS_Vector.jpg',
        /*種別*/classify: itemType.SMG,
        /*射撃モード*/fire_mode: 'S/3/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-22',
        /*近距離*/r_short: '-4',
        /*中距離*/r_middle: '-4',
        /*遠距離*/r_long: '-46',
        /*貫通力*/penetration: bullet.CAL_45ACP_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_45ACP_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_45ACP_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '30',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '2×3',
        /*消音LV*/silence: '3',
        /*本体価格*/item_value: '$2300[14]',
        /*マガジン価格*/mag_value: '$6[9]',
        /*弾薬*/cartridge: '.45ACP',
        /*全長*/item_width: '406/617mm',
        /*重量*/item_weight: '2.500g',
        /*機能*/efficiency: [],
        /*説明*/note: '近接戦闘に使えるコンパクトな兵器システムを求める法執行機関や軍隊向けの短機関銃。 低い銃身軸とスーパーV反動軽減システムにより、最も制御可能な選択射撃操作、または着弾を確認しつつ高速で次弾の発射が可能。'
    },
    //Maxim Defense MDX:510
    {
        /*アイテム名*/item_name: 'Maxim Defense MDX:510',
        /*画像*/items_avatar: 'assets/img/SMG/Maxim_Defense_MDX_510.jpg',
        /*種別*/classify: itemType.PDW,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-22',
        /*近距離*/r_short: '-14',
        /*中距離*/r_middle: '-4',
        /*遠距離*/r_long: '-36',
        /*貫通力*/penetration: bullet.CAL_300BLK_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_300BLK_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_300BLK_MAX,
        /*射程*/range: '200m',
        /*弾数*/mag_round: '',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '2×3',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$2500[15]',
        /*マガジン価格*/mag_value: '$100[10]',
        /*弾薬*/cartridge: '.300 Blackout',
        /*全長*/item_width: '600/640mm',
        /*重量*/item_weight: '2,000g',
        /*機能*/efficiency: [
            'フル-10%'
        ],
        /*説明*/note: 'MAXIM DEFENSEが開発したPDW。扱い易いハンドガードが特徴。弾薬は拳銃弾ではなく5.56mmクラスである300BLK。'
    },
    //China_South_Industries_Group_QSZ_05
    {
            /*アイテム名*/item_name: 'China South Industries Group QSZ-05',
            /*画像*/items_avatar: 'assets/img/SMG/China_South_Industries_Group_QSZ_05.jpg',
            /*種別*/classify: itemType.SMG,
            /*射撃モード*/fire_mode: 'S/3/F',
            /*信頼性*/reliability: '00[99]',
            /*至近*/r_point_blank: '-25',
            /*近距離*/r_short: '-5',
            /*中距離*/r_middle: '-5',
            /*遠距離*/r_long: '-45',
            /*貫通力*/penetration: bullet.CAL_58X21_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_58X21_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_58X21_MAX,
            /*射程*/range: '200m',
            /*弾数*/mag_round: '50',
            /*必要筋力*/kinryoku: '両5/片6',
            /*CP*/size: '2×3',
            /*消音LV*/silence: '5',
            /*本体価格*/item_value: '$2200[13]',
            /*マガジン価格*/mag_value: '$30[10]',
            /*弾薬*/cartridge: '5.8×21mm DCV05',
            /*全長*/item_width: '500mm',
            /*重量*/item_weight: '2,200g',
            /*機能*/efficiency: ['サプレッサー装着不可。音の方向感知の必要達成地+5',
            'HP・AP・亜音速弾使用不可',
            '弾倉交換：[アイテム使用]2回'],
            /*説明*/note: '05式微声短機関銃（05式微声冲锋枪）。「微声」と名が付く通り、通常ではサプレッサーを装着して使用する。開発元は中国南方工業集団。2001年より5.8x21mm DAP92弾を使用する消音サブマシンガンとして開発され、95式自動歩槍を踏襲したブルパップ方式を採用している。'
    },
    //China_South_Industries_Group_QCQ_05
    {
            /*アイテム名*/item_name: 'China South Industries Group QCQ-05',
            /*画像*/items_avatar: 'assets/img/SMG/China_South_Industries_Group_QCQ_05.jpg',
            /*種別*/classify: itemType.SMG,
            /*射撃モード*/fire_mode: 'S/3/F',
            /*信頼性*/reliability: '00[99]',
            /*至近*/r_point_blank: '-20',
            /*近距離*/r_short: '±0',
            /*中距離*/r_middle: '±0',
            /*遠距離*/r_long: '-40',
            /*貫通力*/penetration: bullet.CAL_58X21_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_58X21_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_58X21_MAX,
            /*射程*/range: '400m',
            /*弾数*/mag_round: '50',
            /*必要筋力*/kinryoku: '両5/片6',
            /*CP*/size: '2×3',
            /*消音LV*/silence: '3',
            /*本体価格*/item_value: '$2000[12]',
            /*マガジン価格*/mag_value: '$20[10]',
            /*弾薬*/cartridge: '5.8×21mm DAP92',
            /*全長*/item_width: '500mm',
            /*重量*/item_weight: '2,200g',
            /*機能*/efficiency: ['弾倉交換：[アイテム使用]2回'],
            /*説明*/note: '05式軽型短機関銃（05式軽型冲鋒槍）。QSZ-05と異なりサプレッサーが付属しないモデル。'
    },
    // #endregion

    // #region ハンドガン
    //.460 Rowland
    {
        item_name: '.460 Rowland',
        items_avatar: 'assets/img/Handgun/460-Rowland.jpg',
        classify: itemType.HG,
        fire_mode: 'セミ',
        reliability: '銃依存',
        r_point_blank: '(-5)',
        r_short: '(-5)',
        r_middle: '(-5)',
        r_long: '×',
        penetration: bullet.CAL_460ROW_PNT,
        non_penetration_damage: bullet.CAL_460ROW_MIN,
        penetration_damage: bullet.CAL_460ROW_MAX,
        range: '50m',
        mag_round: '',
        kinryoku: '',
        size: '',
        silence: '(+1)',
        item_value: '',
        mag_value: '元値x3[10]',
        cartridge: '.460 Rowland',
        item_width: '',
        item_weight: '',
        efficiency: [
            '使用可能:M1911系、Glock21、S&W M&P、Sig Sauer P220',
            '.45ACP使用不可'
        ],
        note: 'Johnny Rowlandが.45ACPをもっと強くしたいと開発した弾薬。初速は約1.6倍、エネルギーは約2.7倍にまで上昇した。FCUに専用部品の取り付けが必要で、その場合は.45ACPが使用不可になる。'
    },
    //AF AF2011
    {
        item_name: 'AF AF2011',
        items_avatar: 'assets/img/Handgun/AF_AF2011.jpg',
        classify: itemType.HG,
        fire_mode: '2',
        reliability: '00[99]',
        r_point_blank: '-10',
        r_short: '-10',
        r_middle: '-40',
        r_long: '×',
        penetration: bullet.CAL_45ACP_PNT,
        non_penetration_damage: bullet.CAL_45ACP_MIN,
        penetration_damage: bullet.CAL_45ACP_MAX,
        range: '50m',
        mag_round: '16',
        kinryoku: '両6/片9☆',
        size: '2×2',
        silence: '3',
        item_value: '$1100[11]',
        mag_value: '$10[10]',
        cartridge: '.45ACP',
        item_width: '220mm',
        item_weight: '2,200g',
        efficiency: [
            '★片手-20%',
            '弾倉交換：[アイテム使用]2回',
            '改造不可'
        ],
        note: '.45ACPの威力を倍増させるというコンセプトで作られた、2丁が合体している謎のガバメント。ただ合わせたわけではなく、専用設計である。'
    },
    //Beretta M90 Two
    {
        /*アイテム名*/item_name: 'Beretta M90 Two',
        /*画像*/items_avatar: 'assets/img/Handgun/Beretta_M90_Two.jpg',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_40SW_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_40SW_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_40SW_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '12',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$3200[14]',
        /*マガジン価格*/mag_value: '$10[10]',
        /*弾薬*/cartridge: '.40 S&W',
        /*全長*/item_width: '216mm',
        /*重量*/item_weight: '925g',
        /*機能*/efficiency: [],
        /*説明*/note: '有名なベレッタ92をアップグレードしたバリエーション。デザインを人間工学的に再設計し、より手にフィットするようになっている。現在はM9A1の販売に移行し一般には生産されていないため、希少。日本の警察も採用している。'
    },
    //Beretta M92X
    {
        /*アイテム名*/item_name: 'Beretta M92X',
        /*画像*/items_avatar: 'assets/img/Handgun/Beretta_M92X.png',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-5',
        /*近距離*/r_short: '+5',
        /*中距離*/r_middle: '-34',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '17',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$900[11]',
        /*マガジン価格*/mag_value: '$10[10]',
        /*弾薬*/cartridge: '9mm×19',
        /*全長*/item_width: '211mm',
        /*重量*/item_weight: '1,245g',
        /*機能*/efficiency: [],
        /*説明*/note: 'ベレッタ90シリーズの進化系。ダイナミックな射撃競技やディフェンス目的に最適な最高のパフォーマンスを目指した妥協のないピストルとなっている。'
    },
    //Beretta M93R
    {
        /*アイテム名*/item_name: 'Beretta M93R',
        /*画像*/items_avatar: 'assets/img/Handgun/Beretta_M93R.png',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S/3',
        /*信頼性*/reliability: '99[98]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両6/片6',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$600[14]',
        /*マガジン価格*/mag_value: '$10[10]',
        /*弾薬*/cartridge: '9mm×19',
        /*全長*/item_width: '240mm',
        /*重量*/item_weight: '1,170g',
        /*機能*/efficiency: [
            '★バースト時:片手-10%'
        ],
        /*説明*/note: 'イタリアでテロが頻発していた時期にベレッタが開発した、バースト可能な拳銃。民間用に販売はされておらず、公的機関からの需要があった時のみ生産・供給されている'
    },
    //Beretta M96F Custom:"Smaurai Edge"
    {
        /*アイテム名*/item_name: 'Beretta M96F Custom:"Smaurai Edge"',
        /*画像*/items_avatar: 'assets/img/Handgun/Beretta_M96FC_samurai_edge.jpg',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S/3',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '20',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$500[20]',
        /*マガジン価格*/mag_value: '$10[10]',
        /*弾薬*/cartridge: '9mm×19',
        /*全長*/item_width: '259mm',
        /*重量*/item_weight: '946g',
        /*機能*/efficiency: [
            '隠匿判定-20%',
            '入手にはGMの許可が必要'
        ],
        /*説明*/note: '9mmパラよりも強力な.40SWを使用するM92の派生型。強烈な反動をコントロールするためのマウントレイル付スタビライザーと４ポーテッド・コンペンセイターが標準装備されている。ロングマガジンを使用するため、継戦能力に優れる。'
    },
    //Beretta Px4 Storm
    {
        /*アイテム名*/item_name: 'Beretta Px4 Storm',
        /*画像*/items_avatar: 'assets/img/Handgun/Beretta_Px4_Storm.jpg',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '17',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$240[5]',
        /*マガジン価格*/mag_value: '$3[5]',
        /*弾薬*/cartridge: '9mm×19',
        /*全長*/item_width: '192mm',
        /*重量*/item_weight: '785g',
        /*機能*/efficiency: [],
        /*説明*/note: 'ベレッタ社の新機軸拳銃。ベレッタ 92をはじめとした従来のベレッタ社製の拳銃で広く採用されていたプロップアップ式ショートリコイルでは、銃身下部左右のロッキングブロックによる閉鎖機構上、強度、小型化に限界があり、.40S&W弾（ベレッタM96）よりも大きい口径は用意できなかった。また、サブ・コンパクトサイズまでサイズダウンする事も難しかった。それらを受けて当銃はM8000のようなロテーティング・バレル（回転銃身式）を採用し、全体のサイズはセミ・コンパクトサイズとしている。 '
    },
    //Cz-75 Fullauto
    {
        item_name: 'Cz-75 Fullauto',
        items_avatar: 'assets/img/Handgun/Cz_75_fullauto.jpg',
        classify: itemType.HG,
        fire_mode: 'S/F',
        reliability: '00[99]',
        r_point_blank: '0',
        r_short: '0',
        r_middle: '-40',
        r_long: '×',
        penetration: bullet.CAL_9X19_PNT,
        non_penetration_damage: bullet.CAL_9X19_MIN,
        penetration_damage: bullet.CAL_9X19_MAX,
        range: '50m',
        mag_round: '20',
        kinryoku: '両5/片6',
        size: '1×2',
        silence: '4',
        item_value: '$800[10]',
        mag_value: '$6[9}',
        cartridge: '9x19mm',
        item_width: '217mm',
        item_weight: '1,325g',
        efficiency: [
            'グリップマガジン(マガジンが1つ入るポーチ)を持つ',
            'グリップマガジン使用時、両手+10%、隠匿-20%'
        ],
        note: '世界一美しいCz75の発展型で、フルオート射撃できるようになっている。一般販売されず、法執行機関に供給される。'
    },
    //Cz-Shadow 2
    {
        item_name: 'Cz-Shadow 2',
        items_avatar: 'assets/img/Handgun/Cz_shadow2.jpg',
        classify: itemType.HG,
        fire_mode: 'S',
        reliability: '00[99]',
        r_point_blank: '+2',
        r_short: '+2',
        r_middle: '-36',
        r_long: '×',
        penetration: bullet.CAL_9X19_PNT,
        non_penetration_damage: bullet.CAL_9X19_MIN,
        penetration_damage: bullet.CAL_9X19_MAX,
        range: '50m',
        mag_round: '19',
        kinryoku: '両5/片6',
        size: '1×2',
        silence: '4',
        item_value: '$2100[14]',
        mag_value: '$10[10',
        cartridge: '9x19mm',
        item_width: '217mm',
        item_weight: '1,325g',
        efficiency: [],
        note: '世界一美しいCz75という優れたデザインガンをベースに、ガンスミスによる的確な改造とスポーツシューティング用の高品質なパーツの採用により、さらなる進化を遂げたモデル。射撃の成果を飛躍的に向上させる完璧な銃。'
    },
    //FK BRNO
    {
        /*アイテム名*/item_name: 'FK BRNO',
        /*画像*/items_avatar: 'assets/img/Handgun/FK_BRNO.jpg',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[95]',
        /*至近*/r_point_blank: '+30',
        /*近距離*/r_short: '+20',
        /*中距離*/r_middle: '+10',
        /*遠距離*/r_long: '-50',
        /*貫通力*/penetration: bullet.CAL_75FK_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_75FK_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_75FK_MAX,
        /*射程*/range: '100m',
        /*弾数*/mag_round: '15',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '2×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$15,300[30]',
        /*マガジン価格*/mag_value: '$1,000[25]',
        /*弾薬*/cartridge: '7.5FK',
        /*全長*/item_width: '240g',
        /*重量*/item_weight: '1,300g',
        /*機能*/efficiency: [
            'サプレッサー装着不可', '特殊弾使用不可'
        ],
        /*説明*/note: '伝説の拳銃。CZ-75をイタリアのとある銃器メーカーが改良した、世界最高峰の武器。バレル下に搭載された独自のリコイル減衰システムで反動がほとんどない。7.5FKは、チェコのFK BRNO社が開発した、比較的新しい弾丸である。独特の形状により高い精度と安定性を実現している。弾丸自体はポリマーティップ、ボートテールのデザインで、断面密度と弾道係数が高い。ハンティングと長距離射撃用に設計されており、その両方で高い効果を発揮する。アイアンサイトであっても150m先の静止目標を容易に狙える性能をもつ。ひとつひとつ職人が丁寧に仕上げる伝統工芸品だが、その精密さ故悪環境には弱い。        '
    },
    //H&K P30
    {
        /*アイテム名*/item_name: 'H&K P30',
        /*画像*/items_avatar: 'assets/img/Handgun/HK_P30.jpg',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_40SW_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_40SW_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_40SW_MAX,
        /*射程*/range: '50',
        /*弾数*/mag_round: '13',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$800[10]',
        /*マガジン価格*/mag_value: '$10[10}',
        /*弾薬*/cartridge: '.40 S&W',
        /*全長*/item_width: '181mm',
        /*重量*/item_weight: '840g',
        /*機能*/efficiency: [],
        /*説明*/note: '2006年に発売された警察向け拳銃。女性警察官からの要望によりグリップのバックストラップを交換出来るP2000を開発したが、今度は男性警察官からグリップが細いとの苦情が出るようになり、あわせてグリップパネルも交換出来るようにしたP3000を開発し、商品化した。'
    },
    //H&K USP45 Tactical
    {
        /*アイテム名*/item_name: 'H&K USP45 Tactical',
        /*画像*/items_avatar: 'assets/img/Handgun/HK_usp45_tactical.png',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_45ACP_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_45ACP_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_45ACP_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '12',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$600[9]',
        /*マガジン価格*/mag_value: '$10[10]',
        /*弾薬*/cartridge: '.45ACP',
        /*全長*/item_width: '201mm',
        /*重量*/item_weight: '887g',
        /*機能*/efficiency: [],
        /*説明*/note: 'USPの.45ACP仕様。'
    },
    //Mosin-Nagant Obrez
    {
        /*アイテム名*/item_name: 'Mosin-Nagant Obrez',
        /*画像*/items_avatar: 'assets/img/Handgun/Mosin_Nagant_Obrez.png',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'Volt-action',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '-30',
        /*近距離*/r_short: '-10',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_762X54R_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X54R_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X54R_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '5',
        /*必要筋力*/kinryoku: '両6/片7',
        /*CP*/size: '2×2',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$1000[11]',
        /*マガジン価格*/mag_value: '$10[6]',
        /*弾薬*/cartridge: '7.62x54R',
        /*全長*/item_width: '250mm',
        /*重量*/item_weight: '2,000g',
        /*機能*/efficiency: [
            '片手-40%', '隠匿判定-20%'
        ],
        /*説明*/note: '極限まで切り詰められたMosin-Nagantライフル。精度は格段に落ちているが、初速が速く命中率は悪くない。ロシア革命当時ハンドガンが不足し、代わりとして広く使用された。革命が終わってもパルチザン、ゲリラ、そして1980年代でも犯罪行為に使われた。専用マウントがあるため、レールシステムに対応している。'
    },
    //SIG P365XL
    {
        /*アイテム名*/item_name: 'SIG P365XL',
        /*画像*/items_avatar: 'assets/img/Handgun/SIG_P365XL.jpeg',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '+2',
        /*近距離*/r_short: '+2',
        /*中距離*/r_middle: '-40',
        /*遠距離*/r_long: '※',
        /*貫通力*/penetration: bullet.CAL_9X19_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_9X19_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_9X19_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '12',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '1×1',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$2100[14]',
        /*マガジン価格*/mag_value: '$10[10]',
        /*弾薬*/cartridge: '9x19mm',
        /*全長*/item_width: '168mm',
        /*重量*/item_weight: '688g',
        /*機能*/efficiency: ['DP-1'],
        /*説明*/note: 'SIGの拳銃。護身用や法執行機関のコンシールド（秘匿携行）向けの小型自動拳銃のフルサイズモデル(それでも小さい)。弾薬は強装弾の+P弾を使用する。'
    },
    //Sturm Ruger Ruger LCP
    {
        /*アイテム名*/item_name: 'Ruger LCP',
        /*画像*/items_avatar: 'assets/img/Handgun/Sturm_Ruger_Ruger_LCP.jpg',
        /*種別*/classify: itemType.HG,
        /*射撃モード*/fire_mode: 'S',
        /*信頼性*/reliability: '00[99]',
        /*至近*/r_point_blank: '-2',
        /*近距離*/r_short: '-2',
        /*中距離*/r_middle: '-45',
        /*遠距離*/r_long: '×',
        /*貫通力*/penetration: bullet.CAL_380ACP_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_380ACP_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_380ACP_MAX,
        /*射程*/range: '50m',
        /*弾数*/mag_round: '6',
        /*必要筋力*/kinryoku: '両4/片5',
        /*CP*/size: '1×1',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$360[6]',
        /*マガジン価格*/mag_value: '$3[6]',
        /*弾薬*/cartridge: '.380 ACP',
        /*全長*/item_width: '131mm',
        /*重量*/item_weight: '266g',
        /*機能*/efficiency: ['[隠匿判定]+10%'],
        /*説明*/note: 'アメリカのスターム・ルガー社が発売している拳銃。「LCP」とは、Lightweight Compact Pistol の頭文字を取ったもの。LCPはその名の通り小型軽量を旨とし、フレームにガラス強化ナイロンを採用。.380ACP弾が撃てる拳銃ではKel-Tec社製のP3ATと並び、最小の部類に入る。 '
    },
    //Changfeng_Machine_Shop_QSZ_92
    {
            /*アイテム名*/item_name: 'Changfeng Machine Shop QSZ-92',
            /*画像*/items_avatar: 'assets/img/Handgun/Changfeng_Machine_Shop_QSZ_92.jpg',
            /*種別*/classify: itemType.HG,
            /*射撃モード*/fire_mode: 'S',
            /*信頼性*/reliability: '00[99]',
            /*至近*/r_point_blank: '±0',
            /*近距離*/r_short: '±0',
            /*中距離*/r_middle: '-40',
            /*遠距離*/r_long: '×',
            /*貫通力*/penetration: bullet.CAL_58X21_PNT,
            /*非貫通D*/non_penetration_damage: bullet.CAL_58X21_MIN,
            /*貫通D*/penetration_damage: bullet.CAL_58X21_MAX,
            /*射程*/range: '50m',
            /*弾数*/mag_round: '20',
            /*必要筋力*/kinryoku: '両4/片5',
            /*CP*/size: '1×2',
            /*消音LV*/silence: '4',
            /*本体価格*/item_value: '$650[8]',
            /*マガジン価格*/mag_value: '$20[10]',
            /*弾薬*/cartridge: '5.8×21mm DAP92',
            /*全長*/item_width: '188mm',
            /*重量*/item_weight: '760g',
            /*機能*/efficiency: [],
            /*説明*/note: '92式手槍（92式手枪）。ノリンコが開発した拳銃のうち、初めてポリマーフレームを採用した拳銃である。5.8x21mm DAP92弾は、5.7x28mm弾や4.6x30mm弾の開発コンセプトと同様の、対ボディアーマー貫通弾として開発された。手槍は中国語で拳銃の意である。'
    },
    // #endregion

    // #region LMG
    //FightLite MCR060
    {
        /*アイテム名*/item_name: 'FightLite MCR060',
        /*画像*/items_avatar: 'assets/img/LMG/FightLite_MCR060.jpg',
        /*種別*/classify: itemType.LMG,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '99[98]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-31※',
        /*中距離*/r_middle: '-12',
        /*遠距離*/r_long: '-32',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '400m',
        /*弾数*/mag_round: '200(B)',
        /*必要筋力*/kinryoku: '両8/片-',
        /*CP*/size: '3×5',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$7200[10]',
        /*マガジン価格*/mag_value: '$40[9]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '1,076mm',
        /*重量*/item_weight: '5,500g',
        /*機能*/efficiency: [
            '※次R同一目標攻撃時+20%',
            '制圧射撃時信頼性-1'
        ],
        /*説明*/note: 'M16を改造しベルト弾薬をセットできるようにした銃。元突撃銃なので取り回しは良いが、長時間の連続射撃を行うと放熱面で不具合が起きやすい。'
    },
    //HK_HK21
    {
        /*アイテム名*/item_name: 'H&K HK21E',
        /*画像*/items_avatar: 'assets/img/LMG/HK_HK21.jpg',
        /*種別*/classify: itemType.LMG,
        /*射撃モード*/fire_mode: 'S/3/F',
        /*信頼性*/reliability: '99[98]',
        /*至近*/r_point_blank: '-45※',
        /*近距離*/r_short: '-24※',
        /*中距離*/r_middle: '-3',
        /*遠距離*/r_long: '-23',
        /*貫通力*/penetration: bullet.CAL_762X51_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_762X51_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_762X51_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '100(B)',
        /*必要筋力*/kinryoku: '両8/片-',
        /*CP*/size: '3×5',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$2400[9]',
        /*マガジン価格*/mag_value: '$50[10]',
        /*弾薬*/cartridge: '7.62mm×51',
        /*全長*/item_width: '1,140mm',
        /*重量*/item_weight: '9,300g',
        /*機能*/efficiency: [
            '狙撃-10%',
            'フル-10%',
            '※次R同一目標攻撃時+20%'
        ],
        /*説明*/note: 'G3をベースに開発された汎用機関銃。「狙撃銃に準じた運用も可能」と、H&K社はアピールしている。元が元だけに機関銃としては強度には不安がある。'
    },
    //IMI Negev
    {
        /*アイテム名*/item_name: 'IMI Negev',
        /*画像*/items_avatar: 'assets/img/LMG/IMI_Negev.jpg',
        /*種別*/classify: itemType.LMG,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '00[00]',
        /*至近*/r_point_blank: '-55※',
        /*近距離*/r_short: '-35※',
        /*中距離*/r_middle: '-10',
        /*遠距離*/r_long: '-25',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '400m',
        /*弾数*/mag_round: '35/150(B)',
        /*必要筋力*/kinryoku: '両8/片-',
        /*CP*/size: '3×4',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$4500[12]',
        /*マガジン価格*/mag_value: '$15(35発)[9]/$40(ベルト150発)[9]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '780/1,020mm',
        /*重量*/item_weight: '7,760g',
        /*機能*/efficiency: [
            '狙撃-30%',
            '※次R同一目標攻撃時+20%',
            'セミオート時命中+20%',
            '弾倉交換：[アイテム使用]2回(ベルト弾薬時)'
        ],
        /*説明*/note: 'イスラエルのIsrael Military Industries社がガリルの後継として開発した軽機関銃。小型かつ軽量をコンセプトとしている。セミオート射撃が可能なのが特徴で、民間人に紛れたテロリストを精密射撃により排除できる。'
    },
    //KAC LAMG
    {
        /*アイテム名*/item_name: 'KAC LAMG',
        /*画像*/items_avatar: 'assets/img/LMG/KAC_LAMG.jpg',
        /*種別*/classify: itemType.LMG,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '99[98]',
        /*至近*/r_point_blank: '-40※',
        /*近距離*/r_short: '-20※',
        /*中距離*/r_middle: '-0',
        /*遠距離*/r_long: '-20',
        /*貫通力*/penetration: bullet.CAL_556X45_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_556X45_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_556X45_MAX,
        /*射程*/range: '400m',
        /*弾数*/mag_round: '200(B)',
        /*必要筋力*/kinryoku: '両8/片10☆',
        /*CP*/size: '3×5',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$4500[13]',
        /*マガジン価格*/mag_value: '$40[10]',
        /*弾薬*/cartridge: '5.56mm×45',
        /*全長*/item_width: '900/990mm',
        /*重量*/item_weight: '5,100g',
        /*機能*/efficiency: [
            '☆＝片手撃ち-40%',
            '※次R同一目標攻撃時+20%',
            '制圧射撃時、40発発射で信頼性-1、50発発射でさらに-1'
        ],
        /*説明*/note: 'アメリカのKnight\'s Armament Company社が開発した軽機関銃。5.1kgというベルト給弾式機関銃としては破格の軽さを持ち、ウルティマックス100と同じくコンスタントリコイルシステムを採用することで550~600発/分の低連射速度と低反動を実現している。ストーナーLMGと同じくリード・ナイト氏が実演を行いながらインタビューに答える動画が投稿されており、拳銃のような肩付けしない保持で射撃を行い、反動の少なさをアピールしている。'
    },
    //RPK-16
    {
        /*アイテム名*/item_name: 'RPK-16',
        /*画像*/items_avatar: 'assets/img/LMG/RPK_16.jpg',
        /*種別*/classify: itemType.LMG,
        /*射撃モード*/fire_mode: 'S/F',
        /*信頼性*/reliability: '□[99]',
        /*至近*/r_point_blank: '-40※',
        /*近距離*/r_short: '-30※',
        /*中距離*/r_middle: '-10',
        /*遠距離*/r_long: '-30',
        /*貫通力*/penetration: bullet.CAL_545X39_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_545X39_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_545X39_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '30/95',
        /*必要筋力*/kinryoku: '両8/片-',
        /*CP*/size: '3×5',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$2400[9]',
        /*マガジン価格*/mag_value: '$10(30発)[6]/$50(95発)[10]',
        /*弾薬*/cartridge: '5.45mm×39',
        /*全長*/item_width: '1,076mm',
        /*重量*/item_weight: '4,680g',
        /*機能*/efficiency: [
            '狙撃-25%',
            '※次R同一目標攻撃時+20%',
            '95発マガジンはマガジンポーチに収納不可'
        ],
        /*説明*/note: 'RPKシリーズの最新改良型。先に開発されていたAK-12シリーズの開発で得られた知識、着脱可能な銃身、高められたエルゴノミクス、レールを備えたハンドガードとダストカバーの活用により拡張性の高い近代的なものになっている。AK-12とは30連マガジンを共有できる。BG-30装着可能。'
    },
    // #endregion

    // #region ランチャー
    //H&K GLM
    {
        /*アイテム名*/item_name: 'H&K GLM',
        /*画像*/items_avatar: 'assets/img/Luncher/HK_GLM.jpg',
        /*種別*/classify: itemType.GL,
        /*射撃モード*/fire_mode: 'セミ',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '×',
        /*近距離*/r_short: '-25',
        /*中距離*/r_middle: '-35',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_40MM_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_40MM_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_40MM_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '1',
        /*必要筋力*/kinryoku: '(両6/片8)',
        /*CP*/size: '2×2',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$800[12]',
        /*マガジン価格*/mag_value: '$20(弾のみ1発)[9]',
        /*弾薬*/cartridge: '40mm Grenade',
        /*全長*/item_width: '350mm',
        /*重量*/item_weight: '1,500g',
        /*機能*/efficiency: [
            '中心半径5m:[貫通D]/有効半径10m:[非貫通D]',
            'ピカニティ・レールを持つライフルに装着可。装着時：補器(下)',
            '部位狙い不可'
        ],
        /*説明*/note: 'HK社の新型グレネードランチャー。M203は銃身を前にスライドさせて薬室を開放する構造のため、装填できる弾薬の長さに制限があったが、M320はいかなる長さの弾薬も使用可能である。特に非致死性の弾薬は長いものが多い。セーフティレバーは左右両側から操作できる。アメリカ軍ではM320と呼称され、これはH&Kでの型式名である。'
    },
    // FN EGLM
    {
        /*アイテム名*/item_name: 'FN EGLM',
        /*画像*/items_avatar: 'assets/img/Luncher/eglm.jpg',
        /*種別*/classify: itemType.GL,
        /*射撃モード*/fire_mode: 'セミ',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '×',
        /*近距離*/r_short: '-25',
        /*中距離*/r_middle: '-35',
        /*遠距離*/r_long: '-40',
        /*貫通力*/penetration: bullet.CAL_40MM_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_40MM_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_40MM_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '1',
        /*必要筋力*/kinryoku: '(両6/片8)',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '$1200[12]',
        /*マガジン価格*/mag_value: '$20(弾のみ1発)[9]',
        /*弾薬*/cartridge: '40mm Grenade',
        /*全長*/item_width: '350mm',
        /*重量*/item_weight: '1,100g',
        /*機能*/efficiency: [
            '中心半径5m:[貫通D]/有効半径10m:[非貫通D]',
            '5.56mm NATO弾薬のライフル(非ブルパップ)に装着可。装着時:補器(下)',
            '部位狙い不可'
        ],
        /*説明*/note: 'FN社独自設計のグレネードランチャー。M203よりも軽量で扱いやすい。様々な種類の専用グレネードを発射することができる。'
    },
    // スマートグレネード
    {
        /*アイテム名*/item_name: 'スマートグレネード',
        /*画像*/items_avatar: '',
        /*種別*/classify: itemType.GL,
        /*射撃モード*/fire_mode: 'セミ',
        /*信頼性*/reliability: '□[00]',
        /*至近*/r_point_blank: '×',
        /*近距離*/r_short: '-15',
        /*中距離*/r_middle: '-25',
        /*遠距離*/r_long: '-30',
        /*貫通力*/penetration: bullet.CAL_40MM_PNT,
        /*非貫通D*/non_penetration_damage: bullet.CAL_40MM_MIN,
        /*貫通D*/penetration_damage: bullet.CAL_40MM_MAX,
        /*射程*/range: '300m',
        /*弾数*/mag_round: '1',
        /*必要筋力*/kinryoku: '(両6/片8)',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '1',
        /*本体価格*/item_value: '',
        /*マガジン価格*/mag_value: '$200(弾のみ1発)[10]',
        /*弾薬*/cartridge: '40mm Grenade',
        /*全長*/item_width: '',
        /*重量*/item_weight: '',
        /*機能*/efficiency: [
            '中心半径5m:[貫通D]/有効半径10m:[非貫通D]',
            '部位狙い不可',
            'DP-2',
            'GLMまたはEGLMで使用可能'
        ],
        /*説明*/note: '周囲の環境を測定して、より効果的な攻撃を行うことができるようセンサーが組み込まれた特殊弾。'
    },
    // #endregion 

    // #region 武器戦闘
    {
        /*アイテム名*/item_name: 'ライオットシールド',
        /*画像*/items_avatar: '',
        /*種別*/classify: itemType.MELEE,
        /*射撃モード*/fire_mode: '-',
        /*信頼性*/reliability: '00[00]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '-10',
        /*中距離*/r_middle: 'X',
        /*遠距離*/r_long: 'X',
        /*貫通力*/penetration: '+0',
        /*非貫通D*/non_penetration_damage: '2D6-2',
        /*貫通D*/penetration_damage: '2D6',
        /*射程*/range: '2m',
        /*弾数*/mag_round: '-',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '5',
        /*本体価格*/item_value: '$500[9]',
        /*マガジン価格*/mag_value: '-',
        /*弾薬*/cartridge: '-',
        /*全長*/item_width: 'さまざま',
        /*重量*/item_weight: '3,000g',
        /*機能*/efficiency: [
            '射撃系、格闘系、運動系-10%(強靭除く)',
            '盾による遮蔽:40% 装甲値:4 防御値:0',
            '格闘、武器戦闘、投擲(爆発物除く)の攻撃に対して装甲値+10',
            '片手で武器を使う場合は両手撃ち扱い'
        ],
        /*説明*/note: '暴動鎮圧用の軽量盾。'
    },
    {
        /*アイテム名*/item_name: 'ライフルシールド',
        /*画像*/items_avatar: '',
        /*種別*/classify: itemType.MELEE,
        /*射撃モード*/fire_mode: '-',
        /*信頼性*/reliability: '00[00]',
        /*至近*/r_point_blank: '0',
        /*近距離*/r_short: '-10',
        /*中距離*/r_middle: 'X',
        /*遠距離*/r_long: 'X',
        /*貫通力*/penetration: '+0',
        /*非貫通D*/non_penetration_damage: '2D6-2',
        /*貫通D*/penetration_damage: '2D6',
        /*射程*/range: '2m',
        /*弾数*/mag_round: '-',
        /*必要筋力*/kinryoku: '両5/片6',
        /*CP*/size: '2×5',
        /*消音LV*/silence: '5',
        /*本体価格*/item_value: '$500[9]',
        /*マガジン価格*/mag_value: '-',
        /*弾薬*/cartridge: '-',
        /*全長*/item_width: 'さまざま',
        /*重量*/item_weight: '3,000g',
        /*機能*/efficiency: [
            '射撃系、格闘系、運動系-10%(強靭除く)',
            '盾による遮蔽:40% 装甲値:15 防御値:3',
            '格闘、武器戦闘、投擲(爆発物除く)の攻撃に対して装甲値+10',
            '2x4までの銃器であればペナルティなしで射撃可能'
        ],
        /*説明*/note: '盾に銃を保持するマウントが設けられた特殊シールド。カービンでの戦闘が可能になった。'
    },
    {
        /*アイテム名*/item_name: 'スタンガン',
        /*画像*/items_avatar: 'assets/img/melee/zap-baton.jpg',
        /*種別*/classify: itemType.MELEE,
        /*射撃モード*/fire_mode: '-',
        /*信頼性*/reliability: '00[00]',
        /*至近*/r_point_blank: '-10※',
        /*近距離*/r_short: '0',
        /*中距離*/r_middle: 'X',
        /*遠距離*/r_long: 'X',
        /*貫通力*/penetration: '+0',
        /*非貫通D*/non_penetration_damage: '1D6',
        /*貫通D*/penetration_damage: '2D6',
        /*射程*/range: '2m',
        /*弾数*/mag_round: '-',
        /*必要筋力*/kinryoku: '両-/片3',
        /*CP*/size: '1×2',
        /*消音LV*/silence: '4',
        /*本体価格*/item_value: '$250[6]',
        /*マガジン価格*/mag_value: '-',
        /*弾薬*/cartridge: '-',
        /*全長*/item_width: '300mm',
        /*重量*/item_weight: '300g',
        /*機能*/efficiency: [
            '生物のみ有効',
            'フラッシュライト内蔵',
            '貫通したら対象は[朦朧判定]14',
        ],
        /*説明*/note: '高電圧で相手を威嚇・撃退する携帯用の非殺傷性兵器。家電量販店で販売されている。'
    },
    // #endregion 
]