import { ToolData } from "./toolData";

export const TOOLS: ToolData[] = [
    // テンプレート
    {
        /*名前*/itemName: '',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '',
        /*価格*/itemValue: '',
        /*入手*/itemRare: '',
        /*重量*/itemWeight: '',
        /*機能*/efficiency: [],
        /*説明*/note: '',
    },
    {
        /*名前*/itemName: 'スマートフォン',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '0x0',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '5',
        /*重量*/itemWeight: '500g',
        /*機能*/efficiency: ['通信5', 'カメラ'],
        /*説明*/note: '普通のスマホ。林檎製',
    },
    {
        /*名前*/itemName: 'スマートフォン(軍用)',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '0x0',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '800g',
        /*機能*/efficiency: ['通信8', 'カメラ'],
        /*説明*/note: '耐衝撃・耐水性を備えた丈夫なスマホ。ゲームには向いていない。',
    },
    {
        /*名前*/itemName: 'スマートウォッチ',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '0x0',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '800g',
        /*機能*/efficiency: ['通信8', ''],
        /*説明*/note: 'スマートフォンとの連携や、コンパス、高度計、GPSなどの機能を備えた時計。',
    },
    {
        /*名前*/itemName: 'ポータブルパワーバンク(防水)',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '1x1',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '1800g',
        /*機能*/efficiency: ['電子機器の使用回数を回復（5回分）'],
        /*説明*/note: '電子機器を充電できる小型バッテリー。必要なときに追加の電力を供給する。',
    },
    {
        /*名前*/itemName: 'ソーラーパワーチャージャー',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '1x2',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '1800g',
        /*機能*/efficiency: ['日光を受けている間、電子機器のバッテリーを充電'],
        /*説明*/note: '太陽光発電で電子機器を充電できるコンパクトな充電器。',
    },
    {
        /*名前*/itemName: '改良レーションパック ',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '2x2',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '4000g',
        /*機能*/efficiency: [],
        /*説明*/note: '高エネルギー食品をパックしたもの。一人前３日分。従来からおいしさアップ、生徒からの評価は"味気ないブリティッシュ・カンティーン"',
    },
    {
        /*名前*/itemName: '携帯用水上バイク ',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '4x3',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '8000g',
        /*機能*/efficiency: [],
        /*説明*/note: 'コンパクトで軽量な水上バイクで、水上を移動することができる。',
    },
    {
        /*名前*/itemName: 'ハンドヘルドGPSトラッカー',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '1x1',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '500g',
        /*機能*/efficiency: [],
        /*説明*/note: '小型・軽量のGPSデバイスで、プレイヤーの位置を追跡し、簡単にナビゲートすることができる。',
    },
    {
        /*名前*/itemName: '膨張式スリーピングパッド ',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '2x1',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '1500g',
        /*機能*/efficiency: [],
        /*説明*/note: '簡単に膨らませたり縮めたりできる、快適で軽量なスリーピングパッド。',
    },
    {
        /*名前*/itemName: '防水マッチ',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '0x0',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '500g',
        /*機能*/efficiency: [],
        /*説明*/note: '水に濡れても火がつくマッチ。必要なときにいつでも火を起こせる。',
    },
    {
        /*名前*/itemName: '携帯用浄水ストロー',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '0x0',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '200g',
        /*機能*/efficiency: [],
        /*説明*/note: '小型でコンパクトなストローで、あらゆる水源の水をろ過することができる。',
    },
    {
        /*名前*/itemName: '拡張現実ヘッドセット',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '1x1',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '1000g',
        /*機能*/efficiency: ['ヘルメット併用不可'],
        /*説明*/note: '眼前に敵の位置や目標などの有益な情報を提供するハイテクヘッドセット。',
    },
    {
        /*名前*/itemName: 'ソニックディスラプター',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '1x1',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '1000g',
        /*機能*/efficiency: ['朦朧8', '10失敗でアンバランス'],
        /*説明*/note: '強力な音波を放ち、敵を混乱させ、バランスを崩させる非殺傷兵器。',
    },
    {
        /*名前*/itemName: '',
        /*画像*/itemsAvatar: '',
        /*CP*/size: 'x',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '00g',
        /*機能*/efficiency: [],
        /*説明*/note: '',
    },
    {
        /*名前*/itemName: '',
        /*画像*/itemsAvatar: '',
        /*CP*/size: 'x',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '00g',
        /*機能*/efficiency: [],
        /*説明*/note: '',
    },
    {
        /*名前*/itemName: '',
        /*画像*/itemsAvatar: '',
        /*CP*/size: 'x',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '00g',
        /*機能*/efficiency: [],
        /*説明*/note: '',
    },
    {
        /*名前*/itemName: 'ポータブルUAV',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '2x2',
        /*価格*/itemValue: '$',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '4000g',
        /*機能*/efficiency: ['60分持続', '屋内飛行不可', '耐久10'],
        /*説明*/note: '小型の無人航空機。上空から偵察することができる。',
    },
    {
        /*名前*/itemName: 'ポータブルドラム',
        /*画像*/itemsAvatar: '',
        /*CP*/size: '1x2',
        /*価格*/itemValue: '$1000',
        /*入手*/itemRare: '9',
        /*重量*/itemWeight: '1000g',
        /*機能*/efficiency: ['10分持続', '耐久5', 'ドローン2個セット'],
        /*説明*/note: '偵察や監視に使用できる、小型軽量でボビンのような見た目の二輪ドローン。空は飛べないが、機動性が高いため屋内調査に優れる。',
    }
];